name: wastewatercov19
channels:
  - conda-forge
dependencies:
  - bzip2=1.0.8=h3422bc3_4
  - ca-certificates=2022.9.24=h4653dfc_0
  - libffi=3.4.2=h3422bc3_5
  - libsqlite=3.39.4=h76d750c_0
  - libzlib=1.2.13=h03a7124_4
  - ncurses=6.3=h07bb92c_1
  - openssl=3.0.5=h03a7124_2
  - pip=22.3=pyhd8ed1ab_0
  - python=3.11.0=h93c2e33_0_cpython
  - readline=8.1.2=h46ed386_0
  - setuptools=65.5.0=pyhd8ed1ab_0
  - tk=8.6.12=he1e0b03_0
  - tzdata=2022e=h191b570_0
  - wheel=0.37.1=pyhd8ed1ab_0
  - xz=5.2.6=h57fd34a_0
  - pip:
    - anyio==3.6.2
    - appnope==0.1.3
    - area==1.1.1
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - asttokens==2.1.0
    - attrs==22.1.0
    - backcall==0.2.0
    - beautifulsoup4==4.11.1
    - bleach==5.0.1
    - cffi==1.15.1
    - contourpy==1.0.6
    - cycler==0.11.0
    - debugpy==1.6.3
    - decorator==5.1.1
    - defusedxml==0.7.1
    - entrypoints==0.4
    - executing==1.2.0
    - fastjsonschema==2.16.2
    - fonttools==4.38.0
    - idna==3.4
    - ipykernel==6.16.2
    - ipython==8.6.0
    - ipython-genutils==0.2.0
    - ipywidgets==8.0.2
    - jedi==0.18.1
    - jinja2==3.1.2
    - jsonschema==4.16.0
    - jupyter==1.0.0
    - jupyter-client==7.4.4
    - jupyter-console==6.4.4
    - jupyter-core==4.11.2
    - jupyter-server==1.21.0
    - jupyterlab-pygments==0.2.2
    - jupyterlab-widgets==3.0.3
    - kiwisolver==1.4.4
    - markupsafe==2.1.1
    - matplotlib==3.6.1
    - matplotlib-inline==0.1.6
    - mistune==2.0.4
    - nbclassic==0.4.7
    - nbclient==0.7.0
    - nbconvert==7.2.3
    - nbformat==5.7.0
    - nest-asyncio==1.5.6
    - notebook==6.5.2
    - notebook-shim==0.2.0
    - numpy==1.23.4
    - odfpy==1.4.1
    - packaging==21.3
    - pandas==1.5.1
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==9.3.0
    - plotly==5.11.0
    - prometheus-client==0.15.0
    - prompt-toolkit==3.0.31
    - psutil==5.9.3
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pycparser==2.21
    - pygments==2.13.0
    - pyparsing==3.0.9
    - pyrsistent==0.19.1
    - python-dateutil==2.8.2
    - pytz==2022.5
    - pyzmq==24.0.1
    - qtconsole==5.3.2
    - qtpy==2.2.1
    - scipy==1.9.3
    - send2trash==1.8.0
    - six==1.16.0
    - sniffio==1.3.0
    - soupsieve==2.3.2.post1
    - stack-data==0.6.0
    - tenacity==8.1.0
    - terminado==0.17.0
    - tinycss2==1.2.1
    - tornado==6.2
    - traitlets==5.5.0
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - websocket-client==1.4.1
    - widgetsnbextension==4.0.3
prefix: /usr/local/Caskroom/miniforge/base/envs/wastewatercov19
