name: TDS
channels:
  - defaults
dependencies:
  - python=3.7
  - requests
  - numpy
  - pandas
  - geopandas
  - descartes
  - scipy
  - matplotlib
  - seaborn
  - openpyxl
  - jupyter
  - autopep8
  - conda-forge::jupyter_contrib_nbextensions
  - pymc3
  - scikit-learn
  - pip:
    - pycountry==22.1.10
    - pycountry-convert==0.7.2
    - openpyxl==3.0.9
    - networkx==2.6.3
