name: DataStories
channels:
  - defaults
dependencies:
  - appnope=0.1.0=py38_0
  - attrs=19.3.0=py_0
  - backcall=0.1.0=py38_0
  - bleach=3.1.4=py_0
  - ca-certificates=2020.1.1=0
  - certifi=2020.4.5.1=py38_0
  - dbus=1.13.14=h517e14e_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py38_0
  - expat=2.2.6=h0a44026_0
  - gettext=0.19.8.1=h15daf44_3
  - glib=2.63.1=hd977a24_0
  - icu=58.2=h0a44026_3
  - importlib_metadata=1.5.0=py38_0
  - ipykernel=5.1.4=py38h39e3cac_0
  - ipython=7.13.0=py38h5ca1d4c_0
  - ipython_genutils=0.2.0=py38_0
  - ipywidgets=7.5.1=py_0
  - jedi=0.17.0=py38_0
  - jinja2=2.11.2=py_0
  - jpeg=9b=he5867d9_2
  - jsonschema=3.2.0=py38_0
  - jupyter=1.0.0=py38_7
  - jupyter_client=6.1.3=py_0
  - jupyter_console=6.1.0=py_0
  - jupyter_core=4.6.3=py38_0
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.2.1=h0a44026_6
  - libiconv=1.16=h1de35cc_0
  - libpng=1.6.37=ha441bb4_0
  - libsodium=1.0.16=h3efe00b_0
  - markupsafe=1.1.1=py38h1de35cc_0
  - mistune=0.8.4=py38h1de35cc_1000
  - nbconvert=5.6.1=py38_0
  - nbformat=5.0.6=py_0
  - ncurses=6.2=h0a44026_1
  - notebook=6.0.3=py38_0
  - openssl=1.1.1g=h1de35cc_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py38_1
  - parso=0.7.0=py_0
  - pcre=8.43=h0a44026_0
  - pexpect=4.8.0=py38_0
  - pickleshare=0.7.5=py38_1000
  - pip=20.0.2=py38_3
  - prometheus_client=0.7.1=py_0
  - prompt-toolkit=3.0.4=py_0
  - prompt_toolkit=3.0.4=0
  - ptyprocess=0.6.0=py38_0
  - pygments=2.6.1=py_0
  - pyqt=5.9.2=py38h655552a_2
  - pyrsistent=0.16.0=py38h1de35cc_0
  - python=3.8.2=hc70fcce_0
  - python-dateutil=2.8.1=py_0
  - pyzmq=18.1.1=py38h0a44026_0
  - qt=5.9.7=h468cd18_1
  - qtconsole=4.7.3=py_0
  - qtpy=1.9.0=py_0
  - readline=8.0=h1de35cc_0
  - send2trash=1.5.0=py38_0
  - setuptools=46.2.0=py38_0
  - sip=4.19.8=py38h0a44026_0
  - six=1.14.0=py38_0
  - sqlite=3.31.1=h5c1f38d_1
  - terminado=0.8.3=py38_0
  - testpath=0.4.4=py_0
  - tk=8.6.8=ha441bb4_0
  - tornado=6.0.4=py38h1de35cc_1
  - traitlets=4.3.3=py38_0
  - wcwidth=0.1.9=py_0
  - webencodings=0.5.1=py38_1
  - wheel=0.34.2=py38_0
  - widgetsnbextension=3.5.1=py38_0
  - xz=5.2.5=h1de35cc_0
  - zeromq=4.3.1=h0a44026_3
  - zipp=3.1.0=py_0
  - zlib=1.2.11=h1de35cc_3
prefix: /Users/svanstroud/miniconda3/envs/covid

